name: i_know_ball
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  circular_countdown_timer: ^0.2.4
  http: ^0.13.3
  firebase_core: ^3.9.0
  firebase_database: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: CustomFont
      fonts:
        - asset: fonts/FiraSans-Medium.ttf
  uses-material-design: true

  