// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqf9o1rce14vZ5f_Vn_grCtw6cjCq6tq4',
    appId: '1:723274870510:android:0e8a13604941e743690dff',
    messagingSenderId: '723274870510',
    projectId: 'i-know-ball',
    authDomain: 'i-know-ball.firebaseapp.com',
    databaseURL:
        'https://i-know-ball-default-rtdb.firebaseio.com/', // Add this line
    storageBucket: 'i-know-ball.appspot.com',
    measurementId: 'G-VB2M1FHY7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqf9o1rce14vZ5f_Vn_grCtw6cjCq6tq4',
    appId: '1:723274870510:android:0e8a13604941e743690dff',
    messagingSenderId: '723274870510',
    projectId: 'i-know-ball',
    databaseURL:
        'https://i-know-ball-default-rtdb.firebaseio.com/', // Add this line
    storageBucket: 'i-know-ball.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqf9o1rce14vZ5f_Vn_grCtw6cjCq6tq4',
    appId: '1:723274870510:android:0e8a13604941e743690dff',
    messagingSenderId: '723274870510',
    projectId: 'i-know-ball',
    databaseURL:
        'https://i-know-ball-default-rtdb.firebaseio.com/', // Add this line
    storageBucket: 'i-know-ball.appspot.com',
    iosBundleId: 'com.example.iKnowBall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqf9o1rce14vZ5f_Vn_grCtw6cjCq6tq4',
    appId: '1:723274870510:android:0e8a13604941e743690dff',
    messagingSenderId: '723274870510',
    projectId: 'i-know-ball',
    databaseURL:
        'https://i-know-ball-default-rtdb.firebaseio.com/', // Add this line
    storageBucket: 'i-know-ball.appspot.com',
    iosBundleId: 'com.example.iKnowBall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqf9o1rce14vZ5f_Vn_grCtw6cjCq6tq4',
    appId: '1:723274870510:android:0e8a13604941e743690dff',
    messagingSenderId: '723274870510',
    projectId: 'i-know-ball',
    authDomain: 'i-know-ball.firebaseapp.com',
    databaseURL:
        'https://i-know-ball-default-rtdb.firebaseio.com/', // Add this line
    storageBucket: 'i-know-ball.appspot.com',
    measurementId: 'G-VB2M1FHY7X',
  );
}
